### ISSUE TITLE
Dont know why i am unable to use my prototype commands

### ISSUE THREAD

**Issue by pkapil** [pkapil/FTPClient#1]
var ftp = new FTPClient(options, function() {
	ftp.cwd();
	ftp.list();});

================================================
c:\Users\kp0006\Desktop\NodeJS\FTPClient\index.js:11
ftp.list();
    ^
TypeError: Cannot call method 'list' of undefined
    at c:\Users\kp0006\Desktop\NodeJS\FTPClient\index.js:11:5
    at FTPClient.createSocket (c:\Users\kp0006\Desktop\NodeJS\FTPClient\FTPClient.js:51:9)
    at new module.exports (c:\Users\kp0006\Desktop\NodeJS\FTPClient\FTPClient.js:16:10)
    at Object.<anonymous> (c:\Users\kp0006\Desktop\NodeJS\FTPClient\index.js:9:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

**Comment by arvindr21** [comment]
I don't see the point of a callback in your constructor. Both your constructor and `createSocket()` have synchronous code. 

Take a look at this code

```js
// FTPClient.js
var fs = require("fs");
var net = require("net");
var util = require('util');
var EventEmitter = require('events').EventEmitter;

var FTPClient = function(options) {
    console.log("Welcome to FTP Client Program");
    var self = this;
    Object.keys(options).forEach(function(option) {
        self[option] = options[option];
    });

    EventEmitter.call(this);
    this.port = 21;
    return this.createSocket();
};

util.inherits(FTPClient, EventEmitter);


FTPClient.prototype.createSocket = function() {
    var ftpSocket = new net.Socket();
    ftpSocket.setEncoding('utf8');
    var username = this.user;
    var password = this.password;
    var port = this.port;
    var host = this.host;
    ftpSocket.connect(this.port, this.host, function() {
        console.log('Server is connected');
        ftpSocket.write('USER ' + username + '\n');
        ftpSocket.write('PASS ' + password + '\n');
    });
    ftpSocket.on('data', function(data) {
        console.log('Response From server: \n' + data);
    });

    ftpSocket.on('error', function(err) {
        console.log('Error from server:' + err);
    });

    ftpSocket.on('end', function() {
        console.log('connection ended');
    });

    ftpSocket.on('close', function() {
        console.log('Connection closed');
    });
    this.socket = ftpSocket;
};

FTPClient.prototype.sendFile = function(filePath) {
    if (this.socket) {
        console.log('File Path specified is :' + filePath);
    } else {
        console.log('File Path specified is :' + filePath);
    }
};

FTPClient.prototype.cwd = function(cb) {
    console.log('Current Working Directory:');
    this.socket.write('CWD\n', cb);
};


FTPClient.prototype.list = function(cb) {
    console.log('List ');
    this.socket.write('LIST\n', cb);
};

module.exports = FTPClient;
```

executing the code
```js
// test.js
var FTPClient = require('./FTPClient.js');

var options = {};

var ftp = new FTPClient(options);

console.log('socket.readable', ftp.socket.readable);
console.log('socket.writable', ftp.socket.writable);

ftp.cwd();
ftp.list();
```
output
```bash
$ node test.js
Welcome to FTP Client Program
socket.readable false
socket.writable true
Current Working Directory:
List 
Error from server:Error: connect ECONNREFUSED
Connection closed
```
Does this help?

**Comment by pkapil** [comment]
The cwd aand List are running before the connect method...

$ node index.js
Welcome to FTP Client Program
socket.readable true
socket.writable true
**Current Working Directory:**
**List**
Server is connected
Response From server:
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 4 of 500 allowed.
220-Local time is now 20:29. Server port: 21.
220-This is a private system - No anonymous login
220 You will be disconnected after 15 minutes of inactivity.

Response From server:
530 You aren't logged in

Response From server:
530 You aren't logged in

Response From server:
331 User jmk@pkapil.com OK. Password required

Response From server:
230 OK. Current restricted directory is /

**Comment by arvindr21** [comment]
So, they should run once the connection is established? What is the expected flow?

**Comment by pkapil** [comment]
Yes... After the connection is established ..we want to list the directory structure

**Comment by arvindr21** [comment]
Then, in your original code, instead of executing the callback at the end of `createSocket()`, execute it inside the `connect()` after the connection is established. 
```js
/// snipp snipp
ftpSocket.connect(this.port, this.host, function() {
    console.log('Server is connected');
    ftpSocket.write('USER ' + username + '\n');
    ftpSocket.write('PASS ' + password + '\n');
    if (typeof callback == 'function') {
        callback();
    }
});
/// snipp snipp
```

**Comment by pkapil** [comment]
Arvind... My understanding of call back is wrong or why its getting called Ahead ..infact it should happen after ...i made sure i call inside callback method...

**Code updated in repo**

Welcome to FTP Client Program                                  
Server is connected                                            
socket.readable true                                           
socket.writable true                                           
**Current Working Directory: **                                    
**List **                                                          
Response From server:                                          
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------  
220-You are user number 2 of 500 allowed.                      
220-Local time is now 20:45. Server port: 21.                  
220-This is a private system - No anonymous login              
220 You will be disconnected after 15 minutes of inactivity.   
                                                               
Response From server:                                          
331 User jmk@pkapil.com OK. Password required                  
                                                               
Response From server:                                          
230 OK. Current restricted directory is /                      
                                                               
Response From server:                                          
250 OK. Current directory is /                                 
425 No data connection

**Comment by arvindr21** [comment]
I don't see where it is calling ahead. It is called after the console log inside the `connect()`.

**Comment by pkapil** [comment]
Thanks Arvind.... :)

I understood now

**Comment by arvindr21** [comment]
:+1:
